### ISSUE TITLE
Docs unclear that metadata is opt-in

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-input-kafka#255]
The separate call-out on [metadata fields][] fails to call out that metadata will only be added if `decorate_events` is set to `true`; this leads to confusion and frustration.

[metadata fields]: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#_metadata_fields

**Comment by CloseAtHand** [comment]
On a related subject, the description of decorate_events suggests it will add a field to the event called kafka, not a field within the metadata.

**Comment by ahammani** [comment]
Many thanks @yaauie you solved my issue.

Indeed  the [metadata paragraph](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#_metadata_fields]) should talk about `decorate_events`

**Comment by synhershko** [comment]
Fixed by https://github.com/logstash-plugins/logstash-input-kafka/pull/296

**Comment by nephel** [comment]
A far as I can see, the documentation still does not contain the following line
`Metadata is only added to the event if the decorate_events option is set to true (it defaults to false).` 

is still missing from the current docs https://www.elastic.co/guide/en/logstash/7.1/plugins-inputs-kafka.html

Looks like the PR https://github.com/logstash-plugins/logstash-input-kafka/pull/296 failed
